name: Convert DOCX to PDF and Commit

on:
  push:
    paths:
      - '**/*.docx'
  pull_request:
    paths:
      - '**/*.docx'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Cache pandoc and texlive dependencies
      - name: Cache pandoc and texlive dependencies
        uses: actions/cache@v3
        with:
          path: |
            /root/.cache/pandoc
            /usr/share/texlive
            /var/lib/texmf
          key: ${{ runner.os }}-texlive-${{ hashFiles('**/*.docx') }}

      # Set up pandoc and LaTeX if not cached
      - name: Set up pandoc and LaTeX
        run: |
          # Install pandoc and texlive-full if not already installed
          if ! dpkg-query -l | grep -q pandoc; then
            sudo apt-get update
            sudo apt-get install -y pandoc texlive-full
          fi

      # Convert DOCX to PDF
      - name: Convert DOCX to PDF
        run: |
          mkdir -p pdfs
          # Use find with null-terminated strings to handle spaces and special characters
          find . -name "*.docx" -print0 | while IFS= read -r -d '' docx_file; do
            # Define output PDF filename (same name as DOCX)
            output_pdf="${docx_file%.docx}.pdf"
            # Convert DOCX to PDF using pandoc
            pandoc "$docx_file" -o "$output_pdf"
          done

      # Configure Git user
      - name: Configure git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      # Commit PDF files to the repository
      - name: Commit PDF files
        run: |
          # Stage all the PDFs
          git add '*.pdf'
          # Check if there are any changes (new PDFs)
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            # Commit changes (new PDFs)
            git commit -m "Add/Update PDF files from DOCX conversion"
            # Push changes back to the repository
            git push
          fi
