name: Convert DOCX to PDF on Push

on:
  push:
    paths:
      - '**/*.docx'
  pull_request:
    paths:
      - '**/*.docx'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up cache to avoid reinstalling LibreOffice and dependencies
      - name: Cache LibreOffice and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/libreoffice
            /tmp/apt/*  # Optional, cache apt packages
          key: ${{ runner.os }}-libreoffice-${{ hashFiles('**/*.docx') }}

      # Step 3: Install LibreOffice
      - name: Install LibreOffice
        run: |
          sudo apt-get update
          sudo apt-get install -y libreoffice

      # Step 4: Create PDF folder if it doesn't exist
      - name: Create PDFs folder
        run: mkdir -p pdfs

      # Step 5: Convert DOCX files to PDF
      - name: Convert DOCX to PDF
        run: |
          for file in $(find . -name "*.docx"); do
            # Handle spaces and special characters in filenames
            safe_filename=$(echo "$file" | sed 's/ /\\ /g')
            output_pdf="pdfs/$(basename "${file%.*}.pdf")"
            # Convert the DOCX to PDF using LibreOffice
            libreoffice --headless --convert-to pdf "$safe_filename" --outdir pdfs
          done

      # Step 6: Commit the PDFs back to the repository
      - name: Commit and push PDF files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add pdfs/*.pdf
          git commit -m "Add/Update PDFs from DOCX files"
          git push
